plugins {
    id 'com.android.application'
}

def releaseStoreFile = project.findProperty("RELEASE_STORE_FILE")
def releaseStorePassword = project.findProperty("RELEASE_STORE_PASSWORD")
def releaseKeyAlias = project.findProperty("RELEASE_KEY_ALIAS")
def releaseKeyPassword = project.findProperty("RELEASE_KEY_PASSWORD")

android {
    namespace 'com.jobalistudios.codigoprocesalcivilpe'
    compileSdk 34

    defaultConfig {
        applicationId 'com.jobalistudios.codigoprocesalcivilpe'
        minSdk 30
        targetSdk 34
        versionCode 7
        versionName "1.02"

        testInstrumentationRunner "androidx.test.runner.AndroidJUnitRunner"
    }

    signingConfigs {
        release {
            storeFile file(releaseStoreFile)
            storePassword releaseStorePassword
            keyAlias releaseKeyAlias
            keyPassword releaseKeyPassword
        }
    }

    buildTypes {
        release {
            minifyEnabled true
            shrinkResources true
            proguardFiles getDefaultProguardFile('proguard-android-optimize.txt'), 'proguard-rules.pro'
            signingConfig signingConfigs.release
        }
    }
    compileOptions {
        sourceCompatibility JavaVersion.VERSION_11
        targetCompatibility JavaVersion.VERSION_11
    }
    buildFeatures {
        viewBinding true
    }
}

dependencies {
    def nav_version = "2.8.9"
    implementation "androidx.navigation:navigation-fragment:$nav_version"
    implementation "androidx.navigation:navigation-ui:$nav_version"
    implementation 'androidx.appcompat:appcompat:1.7.0'
    implementation 'com.google.android.material:material:1.12.0'
    implementation 'androidx.constraintlayout:constraintlayout:2.2.1'
    implementation 'androidx.preference:preference:1.2.1'
    implementation 'androidx.lifecycle:lifecycle-livedata-ktx:2.8.7'
    implementation 'androidx.lifecycle:lifecycle-viewmodel-ktx:2.8.7'
    testImplementation 'junit:junit:4.13.2'
    testImplementation 'androidx.test:core:1.6.1'
    testImplementation 'org.robolectric:robolectric:4.14.1'
    androidTestImplementation 'androidx.test.ext:junit:1.2.1'
    androidTestImplementation 'androidx.test.espresso:espresso-core:3.6.1'
    androidTestImplementation 'androidx.test.espresso:espresso-intents:3.6.1'
    androidTestImplementation 'androidx.test:core:1.6.1'
    implementation 'com.google.android.gms:play-services-ads:24.2.0'
    implementation 'com.google.code.gson:gson:2.10.1'



}
